class_name WordleWordList
extends RefCounted

# Curated word lists per length. Mix of common English + light dungeon/puzzle
# theming. All uppercase, ASCII-only, no duplicates.

const WORDS_4: Array[String] = [
	"ARCH","BANE","BARK","BEAM","BELL","BIND","BITE","BLADE",
	"BOLT","BONE","BOOK","BURN","CAGE","CALM","CAPE","CARD",
	"CAVE","CLAD","CLUE","CODE","COIN","COLD","COME","COPY",
	"CORE","DARK","DAWN","DEEP","DICE","DIRE","DOME","DOOR",
	"DOOM","DOWN","DRAW","DROP","DRUM","DUSK","DUST","EACH",
	"ECHO","EDGE","EVEN","EXIT","FACE","FADE","FAIL","FAIR",
	"FALL","FAME","FATE","FEAR","FIND","FIRE","FLAG","FLAT",
	"FLEX","FLIP","FLOW","FOLD","FOLK","FONT","FOOL","FORM",
	"FORT","FOUL","FREE","FROM","FUEL","FULL","FURY","FUSE",
	"GAIN","GALE","GAME","GATE","GAZE","GIFT","GILD","GLOW",
	"GLUE","GOAL","GOLD","GONE","GOOD","GRAB","GREY","GRID",
	"GRIM","GRIP","GROW","GULF","GUST","HACK","HAIL","HALE",
	"HALL","HALT","HAND","HARM","HAZE","HEAL","HEAP","HEAT",
	"HELD","HELM","HELP","HERE","HERO","HIDE","HIGH","HILL",
	"HINT","HOLD","HOLE","HOME","HOOK","HOPE","HOST","HOWL",
	"HUNT","HURT","HYMN","ICON","IRON","ISLE","ITEM","JADE",
	"JAIL","JEST","JOLT","JUMP","JUST","KEEN","KEEP","KEPT",
	"KEYS","KICK","KILL","KIND","KING","KNOT","KNOW","LACE",
	"LAID","LAIR","LAKE","LAMP","LAND","LANE","LARK","LASH",
	"LAST","LATE","LEAD","LEAF","LEAN","LEFT","LEND","LESS",
	"LEVY","LIFE","LIFT","LIMB","LIME","LINE","LINK","LION",
	"LIST","LIVE","LOCK","LOFT","LONE","LONG","LOOK","LORD",
	"LORE","LOSE","LOST","LOUD","LUCK","LURE","LURK","LUSH",
	"MADE","MAGE","MAIL","MAIN","MAKE","MANE","MANY","MARK",
	"MASK","MAZE","MELD","MEND","MESH","MILD","MIND","MINE",
]

const WORDS_5: Array[String] = [
	"ABYSS","ACUTE","ADEPT","AEGIS","AGILE","ALIEN","ALLEY","AMBER",
	"ANGEL","ANVIL","ARENA","ARMOR","ARROW","ATLAS","ATTIC","AWAKE",
	"BADGE","BARON","BEAST","BLACK","BLADE","BLAME","BLANK","BLAZE",
	"BLEAK","BLEND","BLESS","BLIND","BLISS","BLOCK","BLOOM","BOARD",
	"BONES","BOUND","BRACE","BRAIN","BRAND","BRASS","BRAVE","BREAD",
	"BREAK","BRICK","BRIEF","BRINE","BRINK","BROAD","BROOK","BRUTE",
	"BUILD","BURST","CABAL","CAIRN","CARVE","CHAIN","CHALK","CHANT",
	"CHARM","CHASE","CHEAP","CHESS","CHIEF","CHORD","CLAIM","CLAMP",
	"CLASH","CLASP","CLASS","CLEAN","CLEAR","CLIMB","CLING","CLOAK",
	"CLOSE","CLOTH","CLOUD","COACH","CORAL","COUNT","COVER","CRACK",
	"CRAFT","CRANE","CRASH","CRAWL","CREST","CRIME","CROSS","CROWD",
	"CROWN","CRUEL","CRUSH","CRYPT","CURVE","DANCE","DEATH","DECOY",
	"DEITY","DELVE","DENSE","DEPTH","DEVIL","DRAFT","DRAIN","DRAKE",
	"DREAD","DREAM","DRESS","DRIFT","DRINK","DRIVE","DROWN","DWARF",
	"EAGER","EARTH","ELDER","EMBER","EMPTY","EQUAL","EVADE","EVENT",
	"EXACT","EXALT","EXILE","EXTRA","FABLE","FACET","FAITH","FEAST",
	"FIEND","FIGHT","FINAL","FLAME","FLARE","FLASK","FLESH","FLINT",
	"FLOAT","FLOOD","FLOOR","FLORA","FLUTE","FOCUS","FORGE","FOUND",
	"FRAME","FRANK","FRAUD","FRONT","FROST","FRUIT","GHOST","GIANT",
	"GIVEN","GLADE","GLEAM","GLOBE","GLOOM","GLORY","GNOME","GOLEM",
	"GRACE","GRAIN","GRAND","GRANT","GRAPH","GRASP","GRASS","GRAVE",
	"GRAVEL","GREEN","GREET","GUARD","GUESS","GUIDE","GUILD","HAUNT",
	"HAVEN","HEART","HEAVY","HEDGE","HEIST","HERBS","HOARD","HONOR",
	"HOUSE","HUMAN","HYDRA","IVORY","JEWEL","JUDGE","KNIFE","KNEEL",
	"LANCE","LAYER","LEECH","LEVEL","LEVER","LIGHT","LUNAR","MANOR",
]

const WORDS_6: Array[String] = [
	"ABLAZE","ABSORB","AMULET","ANCHOR","ANIMAL","ARCANE","ARCHER","ARMORY",
	"BANNER","BARREN","BEACON","BISHOP","BLIGHT","BRIDGE","BRONZE","BURDEN",
	"CANDLE","CASTLE","CAVERN","CHANCE","CIPHER","CIRCLE","CLERIC","COBALT",
	"COLUMN","COMBAT","CONVEX","COPPER","CORNER","COYOTE","CRADLE","CURATE",
	"DAGGER","DANGER","DEBRIS","DECODE","DEFEND","DELETE","DELUGE","DESERT",
	"DESIGN","DEVICE","DEVOTE","DIVINE","DOMAIN","DRAGON","DUSTED","EMERGE",
	"EMPIRE","ENABLE","ENIGMA","ENTITY","ERRAND","ESCAPE","EVOLVE","EXCEED",
	"EXEMPT","EXPERT","EXPORT","FABRIC","FALCON","FAMINE","FERVOR","FIGURE",
	"FINGER","FLOWER","FORBID","FOREST","FOSSIL","FROZEN","FUMBLE","GARNET",
	"GATHER","GENTLE","GHASTL","GLOBAL","GOBLET","GOBLIN","GOLDEN","GOTHIC",
	"GRAVEL","GROVEL","GROWTH","GUTTER","HALCYO","HAMMER","HANDLE","HARBOR",
	"HERMIT","HIDDEN","HOLLOW","HONEST","HORROR","HUNTER","ICICLE","IGNITE",
	"IMPORT","IMPOSE","INFECT","INJECT","INSECT","INSULT","INTACT","INVADE",
	"INVENT","ISLAND","JASPER","JESTER","JUNGLE","JUSTIC","KERNEL","KNIGHT",
	"LADDER","LAGOON","LAUNCH","LEGEND","LICHEN","LOCKET","LUCENT","LUMBAR",
	"MARBLE","MARKET","MEADOW","MEMOIR","MENACE","METHOD","MIRROR","MORTAR",
	"MOSAIC","MUZZLE","MYSTIC","NATURE","NEBULA","NESTLE","NIMBLE","NORMAL",
	"NOTICE","NUMBER","OBTAIN","OCCULT","ODDITY","ONWARD","OPPOSE","ORACLE",
	"ORPHAN","OUTLET","OUTRUN","PADDLE","PALACE","PARDON","PATROL","PERMIT",
	"PILLAR","PLAGUE","PLEDGE","PLUNGE","POCKET","POISON","PORTAL","POTION",
	"PRAYER","PRIEST","PRINCE","PRISON","PROMPT","PROVEN","PUPPET","PURSUE",
	"PUZZLE","QUARRY","QUARTZ","RAFTER","RANDOM","RANGER","RANSOM","RAVINE",
	"REASON","RECORD","REDUCE","REFUGE","REGRET","RELIEF","REMEDY","REPAIR",
	"REVEAL","RIDDLE","RITUAL","RUBBLE","RUSTIC","SACRED","SAFEST","SAVAGE",
	"SCROLL","SCULPT","SEARCH","SECRET","SENTRY","SHADOW","SHIELD","SHRINE",
]

static func words_for_length(n: int) -> Array:
	match n:
		4: return WORDS_4
		6: return WORDS_6
		_: return WORDS_5

static func is_valid_word(word: String) -> bool:
	var w: String = word.to_upper()
	if w.length() < 4 or w.length() > 6:
		return false
	return w in words_for_length(w.length())
